BEGIN;

CREATE TABLE IF NOT EXISTS public.category (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.services (
  services_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name VARCHAR(150) NOT NULL,
  service_description TEXT,
  service_price NUMERIC(10, 2) NOT NULL,
  deposit_amount NUMERIC(10, 2) NOT NULL,
  duration_minutes INT NOT NULL,
  category_id INT NOT NULL REFERENCES public.category(category_id),
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.appointments (
  appointments_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(255) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(20) NOT NULL,
  service_id INT NOT NULL,
  appointment_datetime TIMESTAMP NOT NULL,
  service_price NUMERIC(10, 2) NOT NULL,
  deposit_amount NUMERIC(10, 2) NOT NULL,
  appointment_status VARCHAR(30) NOT NULL DEFAULT 'pending_payment',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  stripe_checkout_session_id TEXT
);

ALTER TABLE public.appointments
  ADD COLUMN IF NOT EXISTS stripe_checkout_session_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS appointments_stripe_checkout_session_id_unique
  ON public.appointments (stripe_checkout_session_id)
  WHERE stripe_checkout_session_id IS NOT NULL;

INSERT INTO public.category (category_name)
VALUES
  ('Pedicure & Manicure'),
  ('Braids'),
  ('Waxing'),
  ('Lashes')
ON CONFLICT (category_name) DO NOTHING;

COMMIT;
